<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="../MSBuild/Base.props"/>
    <Import Project="../MSBuild/Test.props"/>

    <ItemGroup Label="Project references">
      <ProjectReference Include="..\ContractImplementations.MicrosoftEALogging\ContractImplementations.MicrosoftEALogging.csproj" />
      <ProjectReference Include="..\ContractImplementations.TaskRunJobs\ContractImplementations.TaskRunJobs.csproj" />
      <ProjectReference Include="..\Foundation\Foundation.csproj" />
      <ProjectReference Include="..\Tests.MicrosoftEALogging\Tests.MicrosoftEALogging.csproj" />
    </ItemGroup>

</Project>
