<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="../MSBuild/Base.props"/>
    <Import Project="../MSBuild/Test.props"/>

    <ItemGroup Label="Package references">
        <PackageReference Include="Microsoft.Extensions.Logging"/>
    </ItemGroup>

    <ItemGroup Label="Project references">
        <ProjectReference Include="..\ServiceContainer\ServiceContainer.csproj" />
        <ProjectReference Include="..\ContractImplementations.MicrosoftExtensionsAbstractionsLogging\ContractImplementations.MicrosoftExtensionsAbstractionsLogging.csproj" />
        <ProjectReference Include="..\Foundation\Foundation.csproj"/>
    </ItemGroup>
</Project>
